In [18]:
import geopandas as gpd
import pandas as pd

In [19]:
matchups = gpd.read_file("../data/registros_limpios_matchups_nuevos.json")
print(matchups.shape)
matchups.head()

(3061, 8)

,fecha,fuente,chla,grupo_nombre,estado_trofico,pass_id,delta,geometry
0,2017-01-02,OAN,8.9,RDP-MONTES,M,S2A_MSIL1C_20170104T135052_N0500_R024_T21HUC_2...,2 days 13:50:52.026000,POINT (401164.986 6214585.025)
1,2017-01-02,GEMS,6.8,LDS,O,S2A_MSIL1C_20161229T133222_N0500_R081_T21HXB_2...,3 days 10:27:37.974000,POINT (678380.002 6147956.963)
2,2017-01-02,GEMS,3.2,LDS,O,S2A_MSIL1C_20161229T133222_N0500_R081_T21HXB_2...,3 days 10:27:37.974000,POINT (679045.962 6144090.994)
3,2017-01-02,OAN,4.4,RDP-MONTES,O,S2A_MSIL1C_20170104T135052_N0500_R024_T21HUC_2...,2 days 13:50:52.026000,POINT (402233.023 6210401.038)
4,2017-01-02,OAN,5.9,RDP-MONTES,O,S2A_MSIL1C_20170104T135052_N0500_R024_T21HUC_2...,2 days 13:50:52.026000,POINT (401555.004 6213022.975)

In [20]:
matchups["delta"] = pd.to_timedelta(matchups["delta"])

In [10]:
matchups_3_dias = matchups[~((matchups["grupo_nombre"] == "RN-UPM1") & (matchups["delta"] > pd.Timedelta(days=3)))].copy()
print(matchups.shape)
print(matchups_3_dias.shape)

(3061, 8)
(3061, 8)

In [21]:
matchups_1_dia = matchups[~((matchups["grupo_nombre"] == "RN-UPM1") & (matchups["delta"] > pd.Timedelta(days=1)))].copy()
print(matchups_1_dia.shape)

(2963, 8)

In [22]:
matchups_2_horas = matchups[~((matchups["grupo_nombre"] == "RN-UPM1") & (matchups["delta"] > pd.Timedelta(hours=2)))].copy()
print(matchups_2_horas.shape)

(2890, 8)

In [23]:
matchups_5_horas = matchups[~((matchups["grupo_nombre"] == "RN-UPM1") & (matchups["delta"] > pd.Timedelta(hours=5)))].copy()
print(matchups_5_horas.shape)

(2924, 8)

In [25]:
clases = pd.DataFrame({
    "1 dia": matchups_1_dia.groupby("estado_trofico").size(),
    "2 horas": matchups_2_horas.groupby("estado_trofico").size(),
    #"5 horas": matchups_5_horas.groupby("estado_trofico").size(),
})
clases["diferencia"] = clases["2 horas"] - clases["1 dia"]
clases.loc["Total"] = clases.sum()
clases

                1 dia  2 horas  diferencia
estado_trofico
E                  88       88           0
M                 475      442         -33
O                1510     1476         -34
U                 890      884          -6
Total            2963     2890         -73