In [1]:
import geopandas as gpd
import pandas as pd

In [2]:
gdf = gpd.read_file("../data/oan_gems_seleccion.geojson")

In [3]:
gdf = gdf.drop(columns=["value", "unit"])
gdf = gdf.rename(columns={
    "limite_deteccion": "LD",
    "limite_cuantificacion": "LC"
})

In [6]:
gdf.head(2)

,fecha,Decision,fuente,valor_original,LD,LC,valor_transformado,chla,grupo_nombre,geometry
0,2017-01-02,NaN,OAN,8.900,0.100,0.1,8.900,8.900,RDP-MONTES,POINT (401164.986 6214585.025)
1,2017-01-02,si,GEMS,NaN,NaN,NaN,NaN,6.800000090152,LDS,POINT (678380.002 6147956.963)

In [7]:
gdf.shape

(3902, 10)

In [8]:
mask_non_numeric = pd.to_numeric(gdf['chla'], errors='coerce').isna()
chla = pd.to_numeric(gdf[~mask_non_numeric]["chla"])

In [9]:
chla

0       8.9
1       6.8
2       3.2
3       4.4
4       5.9
       ...
3896    1.5
3897    3.0
3898    1.5
3899    1.5
3900    3.0
Name: chla, Length: 3096, dtype: float64

In [10]:
chla.min(), chla.max()

(np.float64(0.07999999797903), np.float64(470.0))

In [11]:
gdf[mask_non_numeric][["LD", "LC", "chla"]]

       LD   LC   chla
133   NaN  0.1    <LC
138   NaN  0.1    <LC
143   NaN  NaN  <1.00
168   NaN  NaN  <1.00
169   NaN  NaN  <1.00
...   ...  ...    ...
3867  NaN  0.1    <LC
3872  NaN  0.1    <LC
3875  NaN  0.1    <LC
3895  NaN  0.1    <LC
3901  NaN  0.1    <LC

[806 rows x 3 columns]

In [12]:
gdf["LC"].unique()

array([0.1, nan, 1.5, 2.2])

In [13]:
gdf["LD"].unique()

<StringArray>
['0.100', nan, '0.600', '0.700', '0.700000000', '0.100000000']
Length: 6, dtype: str

In [18]:
chla[chla <= 8.0].shape

(2499,)

In [19]:
chla[chla > 8.0].shape

(597,)

In [20]:
chla[chla <= 8.0].shape[0] / chla.shape[0]

0.8071705426356589

In [21]:
chla[chla > 8].shape[0] / chla.shape[0]

0.1928294573643411

In [22]:
ultraoligotrófico = chla[chla < 2.5]
oligotrofico = chla[(chla >= 2.5) & (chla < 8.0)] 
mesotrofico = chla[(chla  >= 8.0) & (chla < 25.0)]
eutrofico = chla[(chla >= 25.0) & (chla <  75)]
hipertrofico = chla[chla >= 75]

In [25]:
U = len(ultraoligotrófico) # MUY saludable
O = len(oligotrofico) # SALUDABLE
M = len(mesotrofico)# OJO
E = len(eutrofico) # PELIGRO
H = len(hipertrofico) # MUERTE

In [26]:
U, O, M, E, H

(928, 1570, 505, 15, 15)