In [91]:
import geopandas as gpd
import pandas as pd

In [92]:
gdf = gpd.read_file("../data/oan_gems_seleccion.geojson")

In [93]:
gdf = gdf.drop(columns=["value", "unit"])
gdf = gdf.rename(columns={
    "limite_deteccion": "LD",
    "limite_cuantificacion": "LC"
})

In [94]:
gdf.head(2)

,fecha,Decision,fuente,valor_original,LD,LC,valor_transformado,chla,grupo_nombre,geometry
0,2017-01-02,si,GEMS,NaN,NaN,NaN,NaN,6.800000090152,LDS,POINT (678380.002 6147956.963)
1,2017-01-02,si,GEMS,NaN,NaN,NaN,NaN,3.1999999191612,LDS,POINT (679045.962 6144090.994)

In [95]:
gdf.shape

(3266, 10)

In [96]:
mask_non_numeric = pd.to_numeric(gdf['chla'], errors='coerce').isna()
chla = pd.to_numeric(gdf[~mask_non_numeric]["chla"])

In [97]:
chla

0        6.8
1        3.2
2        5.9
3       11.4
4        5.9
        ...
3260     1.5
3261     3.0
3262     1.5
3263     1.5
3264     3.0
Name: chla, Length: 2577, dtype: float64

In [98]:
chla.min(), chla.max()

(np.float64(0.07999999797903), np.float64(470.0))

In [102]:
gdf[mask_non_numeric][["LD", "LC", "chla"]]

       LD   LC   chla
95    NaN  0.1    <LC
100   NaN  0.1    <LC
105   NaN  NaN  <1.00
120   NaN  NaN  <1.00
121   NaN  NaN  <1.00
...   ...  ...    ...
3232  NaN  0.1    <LC
3237  NaN  0.1    <LC
3240  NaN  0.1    <LC
3259  NaN  0.1    <LC
3265  NaN  0.1    <LC

[689 rows x 3 columns]

In [ ]:
gdf["LC"].unique()

array([nan, 0.1, 1.5, 2.2])

In [ ]:
gdf["LD"].unique()

<StringArray>
[nan, '0.600', '0.700', '0.700000000']
Length: 4, dtype: str

In [108]:
chla[chla <= 2.5].shape

(763,)

In [ ]:
chla[chla > 2.5].shape

(1814,)

In [114]:
chla[chla <= 8.0].shape[0] / chla.shape[0]

0.8020954598370198

In [115]:
chla[chla > 8].shape[0] / chla.shape[0]

0.1979045401629802